"""Build polling_miss.yaml: how far polls missed in past elections, nationally and by state.

    python forecast/polling_miss.py

Reads 538's archive of polls taken in the last three weeks before each election
(Senate and presidential races by state, and the national generic ballot) and
compares each poll's Dem-minus-Rep margin with the result. Positive misses mean
the polls overstated Democrats. For each cycle it records:

  state_races     the average miss across that cycle's Senate and presidential races
  generic_ballot  the average miss of generic ballot polls
  states          per state, the sum and count of each race's miss beyond that
                  cycle's average, so the model can shrink states with few races

538's archive stops at 2022; 2024 is entered by hand at the bottom (national only).
Rerun after a new archive is published; the model reads the file, not the web.
"""

from __future__ import annotations

import io
from pathlib import Path

import pandas as pd
import requests
import yaml

SOURCE = "https://raw.githubusercontent.com/fivethirtyeight/data/master/pollster-ratings/raw_polls.csv"
HERE = Path(__file__).parent
FIRST_CYCLE = 2010

# Not in 538's archive. Final 2024 polling averages overstated Harris by roughly
# 2.5-3 points nationally and in most battlegrounds; the generic ballot missed by
# about as much. Approximate; edit if better numbers turn up.
HAND_ENTERED = {2024: {"state_races": 2.7, "generic_ballot": 2.7, "states": {}, "approximate": True}}


def main() -> None:
    r = requests.get(SOURCE, timeout=120)
    r.raise_for_status()
    d = pd.read_csv(io.StringIO(r.text))
    d = d[d["type_simple"].isin(["Sen-G", "Pres-G", "House-G-US"]) & (d["cycle"] >= FIRST_CYCLE) & (d["cycle"] % 2 == 0)]
    dem_first = (d["cand1_party"] == "DEM") & (d["cand2_party"] == "REP")
    rep_first = (d["cand1_party"] == "REP") & (d["cand2_party"] == "DEM")
    d = d[dem_first | rep_first].copy()
    d["miss"] = (d["margin_poll"] - d["margin_actual"]) * dem_first[d.index].map({True: 1, False: -1})
    races = d.groupby(["cycle", "type_simple", "location", "race_id"], as_index=False)["miss"].mean()

    out: dict[int, dict] = {}
    for cycle, group in races.groupby("cycle"):
        state = group[group["type_simple"] != "House-G-US"]
        national = state["miss"].mean()
        gb = group.loc[group["type_simple"] == "House-G-US", "miss"]
        states = {}
        for loc, rows in state[state["location"].str.fullmatch(r"[A-Z]{2}") & (state["location"] != "US")].groupby("location"):
            states[loc] = [round(float((rows["miss"] - national).sum()), 2), int(len(rows))]
        out[int(cycle)] = {
            "state_races": round(float(national), 2),
            "generic_ballot": None if gb.empty else round(float(gb.mean()), 2),
            "states": states,
        }
    out.update(HAND_ENTERED)
    header = "# Generated by forecast/polling_miss.py from 538's raw poll archive. Positive = polls overstated Democrats.\n"
    (HERE / "polling_miss.yaml").write_text(header + yaml.safe_dump(out, sort_keys=True, default_flow_style=None, width=120))
    for cycle, v in sorted(out.items()):
        print(cycle, "state races", v["state_races"], "generic ballot", v["generic_ballot"], f"({len(v['states'])} states)")


if __name__ == "__main__":
    main()
