-- Diplomat plate tracker: a checklist of countries and the sightings of
-- their diplomatic license plates. See docs/specs/plate-tracker.md.
--
-- Friends and family read progress on the public side; only the owner logs,
-- edits and deletes sightings.

-- One row per country (or international organization) that has its own
-- diplomatic plate code. plate_codes holds the two-letter country codes from
-- the State Department list: a plate reads D, C or S plus the code for
-- diplomats, consuls and staff, or the code plus D for UN diplomats.
create table public.countries (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique,
  plate_codes text[] not null default '{}'
);

alter table public.countries enable row level security;

create policy "Anyone can read countries" on public.countries
  for select to anon, authenticated
  using (true);

create policy "Owner manages countries" on public.countries
  for all to authenticated
  using ((select public.is_owner())) with check ((select public.is_owner()));

create table public.plate_sightings (
  id uuid primary key default gen_random_uuid(),
  country_id uuid not null references public.countries (id) on delete cascade,
  date_spotted date not null default current_date,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index plate_sightings_country_id_idx on public.plate_sightings (country_id);

create trigger plate_sightings_set_updated_at before update on public.plate_sightings
  for each row execute function public.set_updated_at();

alter table public.plate_sightings enable row level security;

create policy "Anyone can read plate sightings" on public.plate_sightings
  for select to anon, authenticated
  using (true);

create policy "Owner manages plate sightings" on public.plate_sightings
  for all to authenticated
  using ((select public.is_owner())) with check ((select public.is_owner()));

-- The country list, carried over from v1 (src/data/diplomatCodes.ts on the
-- legacy-v1 branch). No v1 sightings are carried over.
insert into public.countries (name, slug, plate_codes) values
  ('Afghanistan', 'afghanistan', array['CS']),
  ('Albania', 'albania', array['GP']),
  ('Algeria', 'algeria', array['TF']),
  ('Andorra', 'andorra', array['HM']),
  ('Angola', 'angola', array['NQ']),
  ('Antigua & Barbuda', 'antigua-and-barbuda', array['FF']),
  ('Argentina', 'argentina', array['HD', 'PR']),
  ('Armenia', 'armenia', array['YA']),
  ('Australia', 'australia', array['XZ']),
  ('Austria', 'austria', array['PA']),
  ('Azerbaijan', 'azerbaijan', array['YZ']),
  ('Bahamas', 'bahamas', array['MP']),
  ('Bahrain', 'bahrain', array['UA']),
  ('Bangladesh', 'bangladesh', array['DP', 'XA']),
  ('Barbados', 'barbados', array['PB']),
  ('Belarus', 'belarus', array['PG']),
  ('Belgium', 'belgium', array['HV']),
  ('Belize', 'belize', array['PC']),
  ('Benin', 'benin', array['HX']),
  ('Bhutan', 'bhutan', array['CT']),
  ('Bolivia', 'bolivia', array['PF']),
  ('Bosnia-Herzegovina', 'bosnia-herzegovina', array['LR']),
  ('Botswana', 'botswana', array['CU']),
  ('Brazil', 'brazil', array['VJ']),
  ('Brunei', 'brunei', array['PM']),
  ('Bulgaria', 'bulgaria', array['QM']),
  ('Burkina Faso', 'burkina-faso', array['QD']),
  ('Burundi', 'burundi', array['CX']),
  ('Cambodia', 'cambodia', array['CB']),
  ('Cameroon', 'cameroon', array['CW']),
  ('Canada', 'canada', array['TG']),
  ('Cape Verde', 'cape-verde', array['AK']),
  ('Central African Republic', 'central-african-republic', array['FG']),
  ('Chad', 'chad', array['JJ']),
  ('Chile', 'chile', array['GY', 'PL']),
  ('Colombia', 'colombia', array['DA']),
  ('Comoros', 'comoros', array['MN']),
  ('Costa Rica', 'costa-rica', array['DB']),
  ('Cote d''Ivoire', 'cote-d-ivoire', array['AC', 'DH']),
  ('Croatia', 'croatia', array['JT']),
  ('Cuba', 'cuba', array['DC']),
  ('Cyprus', 'cyprus', array['DD', 'JY']),
  ('Czech Republic', 'czech-republic', array['SF']),
  ('Denmark', 'denmark', array['DN']),
  ('Djibouti', 'djibouti', array['MK']),
  ('Dominica', 'dominica', array['ST']),
  ('Dominican Republic', 'dominican-republic', array['DF']),
  ('Ecuador', 'ecuador', array['DG']),
  ('Egypt', 'egypt', array['TH']),
  ('El Salvador', 'el-salvador', array['TL']),
  ('Equatorial Guinea', 'equatorial-guinea', array['KG']),
  ('Eritrea', 'eritrea', array['KD']),
  ('Estonia', 'estonia', array['UF']),
  ('Ethiopia', 'ethiopia', array['CC']),
  ('European Economic Communities', 'european-economic-communities', array['LK']),
  ('Fiji', 'fiji', array['KK', 'XC']),
  ('Finland', 'finland', array['TX']),
  ('France', 'france', array['DJ']),
  ('Gabon', 'gabon', array['KN']),
  ('Gambia', 'gambia', array['TW']),
  ('Georgia', 'georgia', array['YG']),
  ('Germany', 'germany', array['LW']),
  ('Ghana', 'ghana', array['TV', 'XE']),
  ('Greece', 'greece', array['DK']),
  ('Grenada', 'grenada', array['TY']),
  ('Guatemala', 'guatemala', array['HW']),
  ('Guinea', 'guinea', array['TU']),
  ('Guinea Bissau', 'guinea-bissau', array['HY']),
  ('Guyana', 'guyana', array['TT']),
  ('Haiti', 'haiti', array['HZ']),
  ('Holy See', 'holy-see', array['FW']),
  ('Honduras', 'honduras', array['JB']),
  ('Hungary', 'hungary', array['KH']),
  ('Iceland', 'iceland', array['TM']),
  ('India', 'india', array['DL']),
  ('Indonesia', 'indonesia', array['QZ']),
  ('International Monetary Fund', 'international-monetary-fund', array['MF']),
  ('International Organization', 'international-organization', array['CN']),
  ('Iran', 'iran', array['DM', 'QX']),
  ('Iraq', 'iraq', array['TF', 'TS']),
  ('Ireland', 'ireland', array['FH']),
  ('Israel', 'israel', array['AV', 'LH', 'LJ', 'SG']),
  ('Italy', 'italy', array['TR']),
  ('Jamaica', 'jamaica', array['KM']),
  ('Japan', 'japan', array['AF']),
  ('Jordan', 'jordan', array['KL']),
  ('Kazakhstan', 'kazakhstan', array['YK']),
  ('Kenya', 'kenya', array['FK']),
  ('Kuwait', 'kuwait', array['JC']),
  ('Kyrgyzstan', 'kyrgyzstan', array['YY']),
  ('Laos', 'laos', array['QN']),
  ('Latvia', 'latvia', array['QP']),
  ('Lebanon', 'lebanon', array['FJ']),
  ('Lesotho', 'lesotho', array['QQ']),
  ('Liberia', 'liberia', array['FL']),
  ('Libya', 'libya', array['FM']),
  ('Liechtenstein', 'liechtenstein', array['TK']),
  ('Lithuania', 'lithuania', array['KJ']),
  ('Luxembourg', 'luxembourg', array['KP']),
  ('Madagascar', 'madagascar', array['AH']),
  ('Malawi', 'malawi', array['QR']),
  ('Malaysia', 'malaysia', array['KR', 'NX']),
  ('Maldives', 'maldives', array['MW']),
  ('Mali', 'mali', array['TQ']),
  ('Malta', 'malta', array['FN']),
  ('Marshall Islands', 'marshall-islands', array['AX', 'CG']),
  ('Mauritania', 'mauritania', array['TP']),
  ('Mauritius', 'mauritius', array['JD']),
  ('Mexico', 'mexico', array['KS']),
  ('Micronesia', 'micronesia', array['CM']),
  ('Moldova', 'moldova', array['YM']),
  ('Monaco', 'monaco', array['KB']),
  ('Mongolia', 'mongolia', array['HN']),
  ('Morocco', 'morocco', array['FP']),
  ('Mozambique', 'mozambique', array['QS']),
  ('Myanmar', 'myanmar', array['CV', 'XD']),
  ('Namibia', 'namibia', array['CK']),
  ('Nauru', 'nauru', array['VM']),
  ('Nepal', 'nepal', array['TN']),
  ('Netherlands', 'netherlands', array['FS']),
  ('New Zealand', 'new-zealand', array['QT']),
  ('Nicaragua', 'nicaragua', array['QU']),
  ('Niger', 'niger', array['QV']),
  ('Nigeria', 'nigeria', array['JF']),
  ('North Korea', 'north-korea', array['GQ']),
  ('North Macedonia', 'north-macedonia', array['LM']),
  ('Norway', 'norway', array['PK', 'XG']),
  ('Oman', 'oman', array['NA']),
  ('Pakistan', 'pakistan', array['QX']),
  ('Palau', 'palau', array['DZ']),
  ('Panama', 'panama', array['AJ']),
  ('Papua New Guinea', 'papua-new-guinea', array['NB']),
  ('Paraguay', 'paraguay', array['NC']),
  ('People''s Republic of China', 'china', array['CY']),
  ('Peru', 'peru', array['TZ']),
  ('Philippines', 'philippines', array['FR']),
  ('Poland', 'poland', array['QW']),
  ('Portugal', 'portugal', array['JG']),
  ('Qatar', 'qatar', array['FT']),
  ('Republic of the Congo', 'republic-of-the-congo', array['AA']),
  ('Romania', 'romania', array['ND']),
  ('Russia', 'russia', array['YR']),
  ('Rwanda', 'rwanda', array['RB']),
  ('Saint Lucia', 'saint-lucia', array['HL']),
  ('Saint Vincent and the Grenadines', 'saint-vincent-and-the-grenadines', array['RC']),
  ('San Marino', 'san-marino', array['RV']),
  ('Sao Tome & Principe', 'sao-tome-and-principe', array['KU']),
  ('Saudi Arabia', 'saudi-arabia', array['KV']),
  ('Senegal', 'senegal', array['RD']),
  ('Seychelles', 'seychelles', array['KW']),
  ('Sierra Leone', 'sierra-leone', array['FX']),
  ('Singapore', 'singapore', array['VK']),
  ('Slovakia', 'slovakia', array['DR']),
  ('Slovenia', 'slovenia', array['JS']),
  ('Solomon Islands', 'solomon-islands', array['BV']),
  ('Somalia', 'somalia', array['JH']),
  ('South Africa', 'south-africa', array['BL', 'DI']),
  ('South Korea', 'south-korea', array['WD']),
  ('Spain', 'spain', array['UH']),
  ('Sri Lanka', 'sri-lanka', array['FV']),
  ('St. Kitts & Nevis', 'st-kitts-and-nevis', array['QL']),
  ('Sudan', 'sudan', array['KX']),
  ('Suriname', 'suriname', array['FZ']),
  ('Swaziland', 'swaziland', array['VL']),
  ('Sweden', 'sweden', array['GC']),
  ('Switzerland', 'switzerland', array['VH']),
  ('Syria', 'syria', array['AQ']),
  ('Tajikistan', 'tajikistan', array['YJ']),
  ('Tanzania', 'tanzania', array['VG']),
  ('Thailand', 'thailand', array['VF']),
  ('Togo', 'togo', array['JQ']),
  ('Tonga', 'tonga', array['HB']),
  ('Trinidad & Tobago', 'trinidad-and-tobago', array['UX']),
  ('Tunisia', 'tunisia', array['JP']),
  ('Turkey', 'turkey', array['GN', 'JK', 'LG', 'XF']),
  ('Turkmenistan', 'turkmenistan', array['YT']),
  ('Uganda', 'uganda', array['AU']),
  ('Ukraine', 'ukraine', array['GD']),
  ('United Arab Emirates', 'united-arab-emirates', array['WB']),
  ('United Kingdom', 'united-kingdom', array['PD', 'WZ']),
  ('Uruguay', 'uruguay', array['RL']),
  ('Uzbekistan', 'uzbekistan', array['AE']),
  ('Vanuatu', 'vanuatu', array['GX']),
  ('Venezuela', 'venezuela', array['LC']),
  ('Vietnam', 'vietnam', array['LD']),
  ('Western Samoa', 'western-samoa', array['WM']),
  ('World Bank', 'world-bank', array['BW']),
  ('Yemen', 'yemen', array['QY']),
  ('Yugoslavia', 'yugoslavia', array['JM']),
  ('Zaire', 'zaire', array['PV']),
  ('Zambia', 'zambia', array['GG']),
  ('Zimbabwe', 'zimbabwe', array['PS']);
